// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}{}

func init() {
	SwaggerInfo.Version = "1.0"
	SwaggerInfo.Host = "localhost:8080"
	SwaggerInfo.BasePath = "/"
	SwaggerInfo.Schemes = []string{"http", "https"}
	SwaggerInfo.Title = "Kenya Info API"
	SwaggerInfo.Description = "Fast and reliable API for Kenya's counties, wards, and leaders data"
}
